# Generated by Django 2.1.7 on 2019-03-09 16:18

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=4500))),
                ('room', models.CharField(max_length=200)),
                ('rates', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(),
                                                                    default=[0, 0, 0, 0, 0], size=5)),
            ],
        ),
    ]
