# Generated by Django 2.1.7 on 2019-03-10 16:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lecture'),
    ]

    operations = [

    ]
