# Generated by Django 2.1.7 on 2019-03-12 16:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190310_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='surveys',
        ),
        migrations.AddField(
            model_name='lecture',
            name='speaker',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start time of lecture'),
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='content',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='content',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='duration',
        ),
        migrations.AddField(
            model_name='lecture',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='End time of lecture'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Survey'),
            preserve_default=False,
        ),
    ]
