# Generated by Django 2.1 on 2019-03-16 10:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190312_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.date, verbose_name='Day')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Day')),
            ],
        ),
        migrations.AlterField(
            model_name='lecture',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.localtime, verbose_name='End time of lecture'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Place'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.localtime, verbose_name='Start time of lecture'),
        ),
    ]
